### ISSUE TITLE
Erro de Certificado (SSLV3_ALERT_BAD_CERTIFICATE)

### ISSUE THREAD

**Issue by jeffersantoss** [andreroggeri/nubank-sync-ynab#7]
[ynabnubanksync-console-1530417326319.txt](https://github.com/andreroggeri/nubank-sync-ynab/files/2152369/ynabnubanksync-console-1530417326319.txt)

2018-07-01 03:52:33 INFO     ynab.py get_nubank_account() - Searching for Nubank account
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/app/.heroku/python/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/app/.heroku/python/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/app/.heroku/python/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/app/.heroku/python/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nubank_sync_ynab/sync.py", line 34, in <module>
    nu = Nubank(NUBANK_LOGIN, NUBANK_PASSWORD)
  File "/app/.heroku/python/lib/python3.6/site-packages/pynubank/nubank.py", line 23, in __init__
    self.authenticate(cpf, password)
  File "/app/.heroku/python/lib/python3.6/site-packages/pynubank/nubank.py", line 33, in authenticate
    request = requests.post(Nubank.TOKEN_URL, json=body, headers=self.headers)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:749)

**Comment by andreroggeri** [comment]
@jeffersantoss esse erro acontece no Heroku ou local na sua máquina ?

EDIT: Acabei de ver que aqui tb acontece.. 😢

**Comment by andreroggeri** [comment]
O problema tá na lib pynubank -> andreroggeri/pynubank#22
